services:
  backend:
    build: backend/
    ports:
      - 1234:1234
    command: ./test_backend_traffic_emulator -c ./config_dev.yaml
  frontend:
    build: frontend/
    ports:
      - 5173:5173

  